{% set name = "tiobeindexpy" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tiobeindexpy-{{ version }}.tar.gz
  sha256: 4f2cae16c9a9b397fc8fc1889bde143a9ad68702b839157bf556d59cb34c76c9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - beautifulsoup4
    - pandas
    - python >={{ python_min }}
    - requests

test:
  imports:
    - tiobeindexpy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/amrrs/tiobeindexpy
  summary: A Python package for getting TIOBE Index
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
